import { RestaurantNavBar } from "./components/RestaurantNavBar";
import { Title } from "./components/Title";
import { Rating } from "./components/Rating";
import { Description } from "./components/Description";
import { Images } from "./components/Images";
import { Reviews } from "./components/Reviews";
import { ReservationCard } from "./components/ReservationCard";
import { Metadata } from "next";
import { PrismaClient } from "@prisma/client";

interface Restaurant {
  id: number;
  name: string;
  images: string[];
  description: string;
  slug: string;
}

const prisma = new PrismaClient();

const fetchRestaurant = async (slug: string): Promise<Restaurant> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      id: true,
      name: true,
      images: true,
      description: true,
      slug: true,
    },
  });

  if(!restaurant) throw new Error();

  return restaurant;
};

// Metadata object automatically replace the head in each page where it is
export const metadata: Metadata = {
  title: "Bicono Restaurant",
  description: "Generated by create next app :)",
  icons: {
    icon: "/cutlery.ico",
  },
};

const RestaurantDetailsPage = async ({params}: {params: {restaurantName: string}}) => {
  const restaurantName = params.restaurantName;
  const restaurant = await fetchRestaurant(restaurantName);

  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavBar slug={restaurant.slug}/>
        <Title name={restaurant.name}/>
        <Rating />
        <Description description={restaurant.description}/>
        <Images images={restaurant.images}/>
        <Reviews />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
};

export default RestaurantDetailsPage;
